### ISSUE TITLE
Schema support

### ISSUE THREAD

**Issue by theo-ardouin** [imankulov/alembic-enums#5]
Hello there!

Would it be possible to add a schema support in the `Column` as well as in the `EnumMigration`?

As it is, trying to "bypass" this issue by using the `schema_name.table` results in an (expected) error.
```python
EnumMigration(
    op=op,
    enum_name="schema_name.enum",
    old_options=EXISTING_OPTIONS,
    new_options=EXISTING_OPTIONS + ["MY_VALUE"],
    columns=[
        Column(
            "schema_name.table",
            "column",
            old_server_default=None,
            new_server_default=None,
        )
    ],
)
```
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "_tmp_schema_name" does not exist
LINE 1: ..._tmp_schema_name.enum_3224  USING category::text::_tmp_schema...
```

Of course, it would make more sense to add a `schema: Optional[str] = None` in both classes for support rather than add the raw string, but I had to test it out :)

**Comment by imankulov** [comment]
@theo-ardouin, thank you so much for your contribution! Your PR #7 has been merged and I have released a new version, [0.4.1](https://pypi.org/project/alembic-enums/0.4.1/).
